import Navbar from '@/components/layouts/navbar/Navbar'
import './globals.css'
import { Roboto } from "next/font/google"
import Footer from '@/components/layouts/footer/Footer'

const roboto = Roboto({
  subsets: ['latin'],
  weight:['300', '400', '500', '700', '900']
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
